//
// Created by 俵京佑 on 2018/10/18.
//

#ifndef IMAGEPROCESSING_IMAGEPROCESSINGHISTOGRAMEXTENSION_H
#define IMAGEPROCESSING_IMAGEPROCESSINGHISTOGRAMEXTENSION_H


class ImageProcessingHistogramExtension {

};


#endif //IMAGEPROCESSING_IMAGEPROCESSINGHISTOGRAMEXTENSION_H
